name: gs3challenge
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  get_it: ^8.0.2
  shimmer: ^3.0.0
  desktop_window: ^0.4.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/data/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets\fonts\Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Mulish-Light.ttf
          weight: 300
        - asset: assets\fonts\Mulish-Regular.ttf
          style: normal      
        - asset: assets\fonts\Mulish-Medium.ttf
          weight: 500       
        - asset: assets\fonts\Mulish-SemiBold.ttf
          weight: 600    
        - asset: assets\fonts\Mulish-Bold.ttf
          weight: 700  
        - asset: assets\fonts\Mulish-ExtraBold.ttf
          weight: 800     
        - asset: assets\fonts\Mulish-Black.ttf
          weight: 900   